package com.mcmiddleearth.actionbar;

import net.kyori.adventure.text.Component;
import org.bukkit.entity.Player;
import org.jetbrains.annotations.Nullable;

public interface HudElement {
    /** Identifies the element in /hudmcme and in the player's stored preferences. */
    String id();

    @Nullable
    Component getComponent(Player player);

    /**
     * Follows the glyph with its element's negative space (U+F000 + elementId, generated by generateFontJson)
     * so it takes up no width in the action bar and never shifts the position of other elements.
     */
    static Component zeroWidth(int elementId, String glyph) {
        return Component.text(glyph + Character.toString(0xF000 + elementId));
    }
}
